### ISSUE TITLE
code metrics not showing for functions containing assignment expressions

### ISSUE THREAD

**Issue by OlafHaag** [sourcery-ai/sourcery-vscode#40] opened 2021-07-14 19:21 UTC
Sourcery doesn't show code metrics if the function or method contains an [assignment expression](https://www.python.org/dev/peps/pep-0572/).

Win10
VS Code 1.58.1
Sourcery 0.9.3
Python 3.9.2

**Comment by Hellebore** [comment] 2021-07-15 09:01
Thanks for raising! This is a duplicate of https://github.com/sourcery-ai/sourcery/issues/130.

Will close this one and handle it from there - am actually working on the issue soon,

**Closed by Hellebore** 2021-07-15 09:01 UTC
