### ISSUE TITLE
[Suspecting caused by this] Version 1.8.0 creating a sqlite database in my project folder

### ISSUE THREAD

**Issue by szw0407** [sourcery-ai/sourcery-vscode#207] opened 2023-08-24 10:22 UTC
I was using sourcery in VSCode and recently in all projects, including those witten in C++ or other languages which sourcery doesn't support, an unexpected folder appeared.

I am using VSCode on Windows 11. For example when I launch VSCode and opened a folder
`D:/example/project`
the folder named `%example%project` was automatically created, inside which is a folder named `chat_history` with the empty SQLite database inside.

This feature appeared to be caused by this extension as when I uninstalled the extension or downgraded it into version 1.7.0, everything was back to normal.

The new feature coming with version 1.8.0 really confused me. I was not, in fact, sure why the files are created as I didn't know this extension has a so-called Chat feature. In fact I was interested if such feature is provided, especially if it can be used in a free plan. However, I am afraid that adding such directories in my project seems improper. I recommend that a better way to store the files be considered, even putting it into `.vscode` is much better as it is usually in `.gitignore` file. However, the folder whose name is the path of my project folder is not quite proper to be added into `.gitignore`.

In fact I am quite glad using the old version as it works quite well. I have been using it for a long time and it really helped me write better codes.

**Comment by brendanator** [comment] 2023-08-25 19:53
Thanks for reporting this @szw0407. Yes, we've confirmed this is caused by us. We have a fix that will be included in the next release

**Comment by szw0407** [comment] 2023-09-11 16:37
This issue seems be fixed in the release today. Thanks.

**Closed** 2023-09-12 15:24 UTC
Labels: next release
